# Generated by Django 3.1.6 on 2021-02-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_auto_20210203_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_productos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Locacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Locacion',
                'verbose_name_plural': 'Locaciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='inventario.catalogoproducto', verbose_name='Catalogo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='inventario.Ubicacion')),
                ('existencia', models.IntegerField(blank=True, null=True, verbose_name='Existencias')),
                ('fecha_entrada', models.DateField(blank=True, null=True, verbose_name='Fecha de entrada')),
                ('perecedero', models.BooleanField(verbose_name='Perecedero')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle Producto',
                'verbose_name_plural': 'Detalle de Productos',
            },
        ),
    ]
