# Generated by Django 3.1.1 on 2020-11-03 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('saldo', models.FloatField(default=0.0, verbose_name='Saldo')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.catalogo', verbose_name='Catalogo de Cuentas')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='SubCuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('saldo', models.FloatField(default=0.0, verbose_name='Saldo')),
                ('es_mayor', models.BooleanField(default=False, verbose_name='Es Cuenta de Mayor')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.catalogo', verbose_name='Catalogo de Cuentas')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.subcuenta', verbose_name='Cuenta Padre')),
                ('cuenta_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuenta', verbose_name='Cuenta Principal')),
            ],
            options={
                'verbose_name': 'SubCuenta',
                'verbose_name_plural': 'SubCuentas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio de Periodo')),
                ('fecha_fin', models.DateField(verbose_name='Fin de Periodo')),
                ('ano', models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2100), django.core.validators.MinValueValidator(2010)], verbose_name='Año')),
                ('creado', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, default='Movimientos diarios', max_length=200, null=True, verbose_name='Descripcion')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidad.libro')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_deber', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Monto Deudor')),
                ('monto_haber', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Monto Acreedor')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.subcuenta', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='contabilidad.periodo', verbose_name='Periodo'),
        ),
    ]
