# Generated by Django 3.1.1 on 2020-11-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20201103_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ('catalogo', 'codigo'), 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='subcuenta',
            options={'ordering': ('catalogo', 'codigo'), 'verbose_name': 'SubCuenta', 'verbose_name_plural': 'SubCuentas'},
        ),
        migrations.AddField(
            model_name='movimiento',
            name='partida',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Movimientos', to='contabilidad.partida', verbose_name='Partida'),
            preserve_default=False,
        ),
    ]
