# Generated by Django 3.1.1 on 2020-11-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20201103_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['libro', 'fecha'], 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentasp', to='contabilidad.catalogo', verbose_name='Catalogo de Cuentas'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.partida', verbose_name='Partida'),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='contabilidad.catalogo', verbose_name='Catalogo de Cuentas'),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='contabilidad.subcuenta', verbose_name='Cuenta Padre'),
        ),
        migrations.AlterField(
            model_name='subcuenta',
            name='cuenta_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentasp', to='contabilidad.cuenta', verbose_name='Cuenta Principal'),
        ),
    ]
