# Generated by Django 3.1.1 on 2020-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20201119_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partida',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Creado'),
            preserve_default=False,
        ),
    ]
