# Generated by Django 3.1.1 on 2021-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20201214_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto_deber',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Monto Debe'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='monto_haber',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Monto Habe'),
        ),
    ]
