# Generated by Django 3.1.1 on 2020-11-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_auto_20201105_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nRegistro', models.CharField(max_length=12, unique=True, verbose_name='Numero de Regisro')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nit', models.CharField(blank=True, max_length=18, null=True, verbose_name='NIT')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('tipo', models.IntegerField(choices=[(1, 'Consumidor Final'), (2, 'Contribuyente'), (3, 'Compras')], verbose_name='Tipo de Libro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='empresas.empresa', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(verbose_name='Correlativo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('nComprobacion', models.IntegerField(blank=True, null=True, verbose_name='Numero de Comprobacion')),
                ('serie', models.IntegerField(blank=True, null=True, verbose_name='Serie')),
                ('corrIntUni', models.IntegerField(blank=True, null=True, verbose_name='Correlativo Interno Unico')),
                ('venExentas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Exentas')),
                ('venGravadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Gravadas')),
                ('ivaDebFiscal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA Debito Fiscal')),
                ('vtVentas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Terceros Ventas')),
                ('vtIVA', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Terceros IVA')),
                ('ivaRetenido', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA Retenido')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total')),
                ('ventasNSujetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas No Sujetas')),
                ('contribuyente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa', verbose_name='Contribuyente')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturact', to='iva.libro')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(verbose_name='Correlativo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cExenteInterna', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Exenta Interna')),
                ('cExenteImportaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Exenta Importaciones')),
                ('cGravadaInterna', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Gravada Interna')),
                ('cGravadaImportaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compra Gravada Importaciones')),
                ('ivaCdtoFiscal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='IVA Cdto Fiscal')),
                ('totalCompra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Compra')),
                ('retencionPretencion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Retencion Pretencion')),
                ('anticipoCtaIva', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Anticipo Cta IVA')),
                ('ivaTerceros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Iva Terceros')),
                ('comprasNSujetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compras No Sujetas')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturacm', to='iva.libro')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativoInicial', models.IntegerField(verbose_name='Correlativo Inicial')),
                ('correlativoFinal', models.IntegerField(verbose_name='Correlativo Final')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('exento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exento')),
                ('locales', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Locales')),
                ('ventaTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Venta Total')),
                ('ventaCtaTerceros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Venta Cta Terceros')),
                ('exportaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exportaciones')),
                ('ventasNSujetas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas No Sujetas')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturacf', to='iva.libro', verbose_name='Libro')),
            ],
        ),
    ]
