# Generated by Django 3.1.6 on 2021-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0003_auto_20201203_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacf',
            name='claseDocumento',
            field=models.CharField(blank=True, choices=[('1', 'IMPRESO POR IMPRENTA O TIQUETES'), ('2', 'FORMULARIO UNICO')], default='1', max_length=1, null=True, verbose_name='Clase de Documento'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='exportacionesCA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exportaciones Dentro del Area Centroamericana'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='exportacionesNoCA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exportaciones Fuera del Area Centroamericana'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='numeroControlInterno',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Control Interno'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='numeroRegistradora',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Numero de Maquina Registradora'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='numeroResolucion',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Numero de Resolucion'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='numeroSerie',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Serie de Documento'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('01', 'FACTURA'), ('02', 'FACTURA DE VENTAS SIMPLIFICADAS'), ('10', 'TIQUETES DE MAQUINA REGISTRADORA'), ('11', 'FACTURA DE EXPORTACION')], default='01', max_length=2, null=True, verbose_name='Tipo de Documetno'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='ventasInternasExentas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Internas Exentas no Sujetas a Proporcionalidad'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='ventasZonasFrancas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas a Zonas Francas y DPA(Tasa Cero)'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='cExenteInternaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Internaciones Exentas y/o No Sujetas'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='cGravadaImportacionesServicios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Importaciones Gravadas de Servicios'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='cGravadaInternaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Internaciones Gravadas de Bienes'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='claseDocumento',
            field=models.CharField(blank=True, choices=[('1', 'IMPRESO POR IMPRENTA O TIQUETES'), ('2', 'FORMULARIO UNICO'), ('3', 'OTROS')], default='1', max_length=1, null=True, verbose_name='Clase de Documento'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='numeroDocumento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('03', 'COMPROBANTE DE CREDITO FISCAL'), ('05', 'NOTA DE CREDITO'), ('06', 'NOTA DE DEBITO'), ('11', 'FACTURA DE EXPORTACION'), ('12', 'DECLARACION DE MERCANCIAS'), ('13', 'MANDAMIENTO DE INGRSO')], default='03', max_length=2, null=True, verbose_name='Tipo de Documetno'),
        ),
        migrations.AddField(
            model_name='facturact',
            name='claseDocumento',
            field=models.CharField(blank=True, choices=[('1', 'IMPRESO POR IMPRENTA O TIQUETES'), ('2', 'FORMULARIO UNICO')], default='1', max_length=1, null=True, verbose_name='Clase de Documento'),
        ),
        migrations.AddField(
            model_name='facturact',
            name='numeroControlInterno',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Control Interno'),
        ),
        migrations.AddField(
            model_name='facturact',
            name='numeroDocumento',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Documento'),
        ),
        migrations.AddField(
            model_name='facturact',
            name='numeroResolucion',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Numero de Resolucion'),
        ),
        migrations.AddField(
            model_name='facturact',
            name='numeroSerie',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Serie de Documento'),
        ),
        migrations.AddField(
            model_name='facturact',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('03', 'COMPROBANTE DE CREDITO FISCAL'), ('05', 'NOTA DE CREDITO'), ('06', 'NOTA DE DEBITO')], default='03', max_length=2, null=True, verbose_name='Tipo de Documetno'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='correlativoFinal',
            field=models.IntegerField(blank=True, null=True, verbose_name='NUMERO DE DOCUMENTO(AI)'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='correlativoInicial',
            field=models.IntegerField(blank=True, null=True, verbose_name='NUMERO DE DOCUMENTO(DEL)'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='exento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Exentas'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='locales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ventas Gravadas Locales'),
        ),
        migrations.AlterField(
            model_name='facturacm',
            name='cExenteImportaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Importacion Exentas y/o No Sujetas'),
        ),
        migrations.AlterField(
            model_name='facturacm',
            name='cExenteInterna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compras Internas Exentas y/o No Sujetas'),
        ),
        migrations.AlterField(
            model_name='facturacm',
            name='cGravadaImportaciones',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Importaciones Gravadas de Bienes'),
        ),
        migrations.AlterField(
            model_name='facturacm',
            name='cGravadaInterna',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Compras Internas Gravadas'),
        ),
        migrations.AlterField(
            model_name='facturacm',
            name='ivaCdtoFiscal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Credito Fiscal'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correlativo'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='ivaDebFiscal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='IVA Debito Fiscal'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='venExentas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Ventas Exentas'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='venGravadas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Ventas Gravadas'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='ventasNSujetas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Ventas No Sujetas'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='vtIVA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Debito Fiscal Ventas a Terceros'),
        ),
        migrations.AlterField(
            model_name='facturact',
            name='vtVentas',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Ventas a Terceros no Domiciliados'),
        ),
    ]
