# Generated by Django 3.1.6 on 2021-04-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0004_auto_20210407_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=18, null=True, verbose_name='NIT'),
        ),
    ]
