# Generated by Django 3.1.6 on 2021-04-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0005_auto_20210410_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacm',
            name='correlativo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Correlativo'),
        ),
    ]
