# Generated by Django 3.1.6 on 2021-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0006_auto_20210412_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacf',
            name='numeroControlInterno',
        ),
        migrations.AddField(
            model_name='facturacf',
            name='exportacionesServicios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Exportaciones de Servicios'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='numeroControlInternoAl',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Control Interno (AL)'),
        ),
        migrations.AddField(
            model_name='facturacf',
            name='numeroControlInternoDel',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Numero de Control Interno (DEL)'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='correlativoFinal',
            field=models.IntegerField(blank=True, null=True, verbose_name='NUMERO DE DOCUMENTO(AL)'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='ventaCtaTerceros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Venta Cta Terceros No Domiciliados'),
        ),
    ]
