# Generated by Django 3.1.6 on 2021-04-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0007_auto_20210414_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacm',
            name='numeroSerie',
            field=models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Numero de Serie'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='numeroControlInternoAl',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Numero de Control Interno (AL)'),
        ),
        migrations.AlterField(
            model_name='facturacf',
            name='numeroControlInternoDel',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Numero de Control Interno (DEL)'),
        ),
    ]
