# Generated by Django 3.1.6 on 2021-05-11 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0008_auto_20210421_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetencionCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('numeroDocumento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Documento')),
                ('numeroSerie', models.CharField(blank=True, default='', max_length=14, null=True, verbose_name='Numero de Serie')),
                ('retencion', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Retencion')),
                ('monto_sujeto', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Monto Sujeto')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retenciones', to='iva.libro')),
            ],
            options={
                'verbose_name': 'RetencionCompra',
                'verbose_name_plural': 'Retenciones Compras',
            },
        ),
    ]
