# Generated by Django 3.1.6 on 2021-05-14 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0009_retencioncompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencioncompra',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iva.empresa', verbose_name='Empresa'),
        ),
    ]
