# Generated by Django 3.1.6 on 2021-05-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0010_retencioncompra_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencioncompra',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('07', 'COMPROBANTE DE Retencion'), ('05', 'NOTA DE CREDITO'), ('06', 'NOTA DE DEBITO'), ('2%', 'ANTICIPO CUENTA IVA')], default='05', max_length=2, null=True, verbose_name='Tipo de Documetno'),
        ),
    ]
