# Generated by Django 3.1.6 on 2021-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0011_retencioncompra_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencioncompra',
            name='es_percepcion',
            field=models.BooleanField(default=False, verbose_name='Es percepcion 1%'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('07', 'COMPROBANTE DE Retencion'), ('03', 'COMPROBANTE DE CREDITO FISCAL'), ('05', 'NOTA DE CREDITO'), ('06', 'NOTA DE DEBITO'), ('2%', 'ANTICIPO CUENTA IVA')], default='05', max_length=2, null=True, verbose_name='Tipo de Documetno'),
        ),
    ]
