# Generated by Django 3.1.6 on 2024-04-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iva', '0012_auto_20210614_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacm',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('1', 'Costo'), ('2', 'Gasto'), ('0', 'Periodos tributarios anteriores a 02/2024')], default='1', max_length=1, null=True, verbose_name='Clasificacion'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', 'Industria'), ('2', 'Comercio'), ('3', 'Agropecuaria'), ('4', 'Servicios, Profesiones, Artes y Oficios'), ('0', 'Periodos tributarios anteriores a febrero de 2024')], default='1', max_length=1, null=True, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='tipo_compra',
            field=models.CharField(blank=True, choices=[('1', 'Gastos de Venta sin Donación'), ('2', 'Gastos de Administración sin Donación'), ('3', 'Gastos Financieros sin Donación'), ('4', 'Costo Articulos Producidos/Comprados Importaciones/Internaciones'), ('5', 'Costo Articulos Producidos/Comprados Interno'), ('6', 'Costos Indirectos de Fabricación'), ('7', 'Mano de obra'), ('0', 'Periodos tributarios anteriores a febrero de 2024')], default='1', max_length=1, null=True, verbose_name='Tipo de Costo/Gasto'),
        ),
        migrations.AddField(
            model_name='facturacm',
            name='tipo_operacion',
            field=models.CharField(blank=True, choices=[('1', 'Gravada'), ('2', 'Exenta o No Gravada'), ('3', 'Excluido o no constituye iva'), ('4', 'Mixta (2)'), ('0', 'Periodos tributarios anteriores a 02/2024')], default='1', max_length=1, null=True, verbose_name='Tipo de Operacion'),
        ),
        migrations.AlterField(
            model_name='retencioncompra',
            name='tipoDocumento',
            field=models.CharField(blank=True, choices=[('07', 'COMPROBANTE DE Retencion'), ('03', 'COMPROBANTE DE CREDITO FISCAL'), ('05', 'NOTA DE CREDITO'), ('06', 'NOTA DE DEBITO'), ('2%', 'ANTICIPO CUENTA IVA')], default='05', max_length=2, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
