# Generated by Django 3.1.1 on 2020-11-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nit',
            field=models.CharField(default=None, max_length=17, unique=True, verbose_name='NIT'),
            preserve_default=False,
        ),
    ]
