# Generated by Django 3.1.6 on 2021-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20201105_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Direccion'),
        ),
    ]
