# Generated by Django 3.1.6 on 2021-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_auto_20210203_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='inventario',
            field=models.BooleanField(default=False, verbose_name='Inventario'),
        ),
    ]
