# Generated by Django 3.1.6 on 2024-11-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DUI'),
        ),
    ]
