# Generated by Django 3.2.10 on 2022-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dui',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='DUI'),
        ),
    ]
