# Generated by Django 3.1.6 on 2021-03-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0004_empresa_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talonario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talonarios', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Talonario',
                'verbose_name_plural': 'Talonarios',
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('talonario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='control.talonario', verbose_name='Talonario')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidads',
            },
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='Mensualidad', verbose_name='Descripcion')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(verbose_name='Estado')),
                ('cancelado', models.BooleanField(verbose_name='Cancelado')),
                ('mensualidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.mensualidad')),
            ],
        ),
    ]
