# Generated by Django 3.1.6 on 2021-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='fecha_acordada_pago',
            field=models.DateField(default=None, verbose_name='Fecha Acordada de pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobro',
            name='fecha_real_pago',
            field=models.DateField(default=None, verbose_name='Fecha De Pago'),
            preserve_default=False,
        ),
    ]
