# Generated by Django 3.1.6 on 2021-04-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210322_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='mensualidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='control.mensualidad'),
        ),
    ]
